name: GCP Login
description: "Authenticate to GCP with a service account and optionally configure Docker for Artifact Registry"

inputs:
  service-account-key:
    description: "JSON key for the GCP service account"
    required: true
  configure-docker:
    description: "If 'true', configure Docker auth for Artifact Registry"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    # 1) Install gcloud + GKE auth plugin
    - name: Install gcloud CLI and GKE auth plugin
    # This action installs the gcloud SDK and the gke-gcloud-auth-plugin component
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
        install_components: gke-gcloud-auth-plugin

    # 2) Activate the service account and set the project
    - name: Activate service account & set project
      shell: bash
      env:
        PROJECT_ID: ${{ env.PROJECT_ID }}
      run: |
        # Write the JSON key into a temp file
        echo '${{ inputs.service-account-key }}' > /tmp/gcp-key.json

        # Authenticate as the service account
        gcloud auth activate-service-account \
          --key-file=/tmp/gcp-key.json

        # Set the default project for all subsequent gcloud/kubectl commands
        gcloud config set project "$PROJECT_ID"

        # Tell kubectl to use the new GKE auth plugin
        echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> "$GITHUB_ENV"

    # 3) Optionally configure Docker for Artifact Registry
    - name: Configure Docker for Artifact Registry (optional)
      if: inputs.configure-docker == 'true'
      shell: bash
      run: |
        gcloud auth configure-docker europe-west2-docker.pkg.dev --quiet