name: "GCP Login"
description: "Authenticate to GCP using a service account and optionally configure Docker for Artifact Registry"

inputs:
  service-account-key:
    description: "JSON service account key"
    required: true
  configure-docker:
    description: "Set to true to configure Docker for Artifact Registry"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    # We checkout the repo so kubectl/manifests are available if needed
    - name: Checkout code
      uses: actions/checkout@v4

    # Install gcloud CLI in the runner
    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        # PROJECT_ID will be passed via env from the calling workflow
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: false

    # Log in to GCP using the service account
    - name: Authenticate to GCP
      shell: bash
      run: |
        # Write the JSON key into a temp file
        echo '${{ inputs.service-account-key }}' > /tmp/gcp-key.json

        # Activate the service account
        gcloud auth activate-service-account \
          --key-file=/tmp/gcp-key.json

        # Set the project so all gcloud commands know where to work
        gcloud config set project "$PROJECT_ID"

    # Optionally configure Docker to push to Artifact Registry
    - name: Configure Docker for Artifact Registry (optional)
      if: inputs.configure-docker == 'true'
      shell: bash
      run: |
        gcloud auth configure-docker europe-west2-docker.pkg.dev --quiet